<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrzetargiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrzetargiRepository extends EntityRepository {
    
    public function getAuctiongByLocation($location) {
        $em = $this->getEntityManager();      
        $result = $em->createQueryBuilder('p')
            ->addSelect("MATCH_AGAINST (p.miejscowosc, p.wojewodztwo, :searchterm 'IN NATURAL MODE') as score")
            ->add('where', 'MATCH_AGAINST(p.miejscowosc, p.wojewodztwo, :searchterm) > 0.8')
            ->setParameter('searchterm', "$location")
            ->orderBy('score', 'desc')
            ->getQuery()
            ->getResult();
        
        return $result;
    }
    
    
}

        /*$em = $this->getEntityManager();

        $query = $em->createQuery(
            "SELECT person
            FROM CodersLabBundle:Persons person WHERE
            person.surname LIKE '$partOfName%'");

        return $query->getResult();*/

