<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrzetargiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrzetargiRepository extends EntityRepository {
    
    public function getByLocation($id, $location) {
        $query = $this->getEntityManager()->createQuery(
            "SELECT p
            FROM AppBundle:Przetargi p WHERE
            p.id = $id AND (p.miejscowosc LIKE '$location' OR p.wojewodztwo LIKE '$location')"
        );
        return $query->getResult();
    }
    
    
    
}

        /*$em = $this->getEntityManager();

        $query = $em->createQuery(
            "SELECT person
            FROM CodersLabBundle:Persons person WHERE
            person.surname LIKE '$partOfName%'");

        return $query->getResult();*/

